name: Build Windows and Linux artifacts

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Install compiler tools
        run: |
          sudo apt-get update
          sudo apt-get install llvm automake libxml2-dev gperf build-essential libboost-all-dev cmake make protobuf-compiler
      - name: Compile UDBM wrapper
        run: |
          cd dbm
          cmake -B build/
          cmake --build build/
      - uses: actions-rs/toolchain@v1
        with:
          profile: release
          toolchain: stable
          override: true
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: reveaal-linux
          path: '${{runner.workspace}}/target/release/Reveaal'