name: Build Windows and Linux artifacts

on:
  - push

jobs:
  build-linux:
    name: Build Reveaal for Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Install compiler tools
        run: |
          sudo apt-get update
          sudo apt-get install llvm automake libxml2-dev gperf build-essential libboost-all-dev cmake make protobuf-compiler
      - name: Compile UDBM wrapper
        run: |
          cd dbm
          cmake -B build/
          cmake --build build/
      - uses: actions-rs/toolchain@v1
        with:
          profile: release
          toolchain: stable
          override: true
      - uses:
      - name: Upload artifacts 
        uses: actions/upload-artifact@v2
        with:
          name: reveaal-linux
          path: '${{runner.workspace}}/target/release/Reveaal'

  build-win:
    name: Build Reveaal for Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Install compiler tools
        run: |
          sudo apt-get update
          sudo apt-get install llvm automake libxml2-dev gperf build-essential libboost-all-dev cmake make protobuf-compiler mingw-w64
      - name: Compile UDBM wrapper
        run: |
          cd dbm
          cmake -B build/ -D CMAKE_TOOLCHAIN_FILE=toolchain-x86_64-w64-mingw32.cmake
          cmake --build build/
      - uses: actions-rs/toolchain@v1
        with:
          profile: release
          toolchain: stable
          target: x86_64-pc-windows-gnu
          override: true
      - uses:
      - name: Upload artifacts 
        uses: actions/upload-artifact@v2
        with:
          name: reveaal-win
          path: '${{runner.workspace}}/target/release/Reveaal.exe'